#!/usr/bin/env bash
#
# Bash completion for TimeWarrior
#
# Copyright (C) 2017  Thomas Lauf
# taken from https://github.com/lauft/timew-bashcompletion
#
function __get_commands()
{
  echo "annotate cancel config continue day delete diagnostics end export extensions fill gaps get help join lengthen modify month move report resize shorten show split start stop summary tag tags track undo untag week"
}

function __get_options()
{
  echo "--help --version"
}

function __get_ids()
{
  seq -f "@%g" 1 "$( timew get dom.tracked.count )"
}

function __get_tags()
{
  timew tags | awk '{if(NR>3)print $1}'
}

function __get_extensions()
{
  timew extensions | awk '{if(NR>6)print $1}'
}

function __has_entered_id()
{
  for word in "${COMP_WORDS[@]}" ; do
    if [[ "${word}" =~ ^@ ]] ; then
      return 0
    fi
  done

  return 1
}

function __is_entering_id()
{
  if [[ "${COMP_WORDS[COMP_CWORD]}" =~ @[0-9]* ]] ; then
    return 0
  else
    return 1
  fi
}

function _timew()
{
  local cur first
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  first="${COMP_WORDS[1]}"

  case "${first}" in
    cancel|config|diagnostics|day|extensions|get|month|show|undo|week)
      wordlist=""
      ;;
    continue|delete|join|lengthen|move|resize|shorten|split)
      wordlist=$( __get_ids )
      ;;
    export|gaps|start|stop|tags|track)
      wordlist=$( __get_tags )
      ;;
    modify)
      if __is_entering_id ; then
        wordlist=$( __get_ids )
      elif __has_entered_id ; then
        wordlist=$( '<[date]time>' )
      else
        wordlist="start end"
      fi
      ;;
    summary)
      wordlist="$( __get_tags ) :yesterday :day :week :month :quarter :year :lastweek :lastmonth :lastquarter :lastyear today"
      ;;
    tag|untag)
      if __is_entering_id ; then
        wordlist=$( __get_ids )
      elif __has_entered_id ; then
        wordlist=$( __get_tags )
      else
        wordlist=$( __get_ids )
      fi
      ;;
    report)
      wordlist=$( __get_extensions )
      ;;
    help)
      wordlist="$( __get_commands ) interval hints date duration dom"
      ;;
    --*)
      wordlist=$( __get_options )
      ;;
    *)
      wordlist=$( __get_commands )
      ;;
  esac

  COMPREPLY=($( compgen -W "${wordlist}" -- "${cur}" ))
}

complete -F _timew timew
